### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by LSTANCZYK** [zBritva/handlebars-powerbi#1]
I love the visual. It is great. 
I am using it to build a dynamic HTML text and when testing I noticed that there is no ability to scroll if the content is longer than what fits in the viewport. 

I even tried to wrap everything in a div with css `style="overflow-y:scroll;"`. 

Would it be possible to add scrolling functionality?

**Comment by zBritva** [comment]
Add height:100%:

```html
<div style="overflow-y:scroll;height:100%">
```

**Comment by zBritva** [comment]
@LSTANCZYK The parent container should be limited by some size (should have fixed width or height or take 100% of width or height of own parent (in case of the visual it's visual container) )

**Comment by zBritva** [comment]
http://localhost:3000/docs/handelbars-visual/faq#how-to-add-scrolling
